services:
  api:
    image: amineelgaini/online-shop-api
    build:
      context: .
      target: production
    ports:
      - "8000:8000"
    env_file:
      - .env
    
    environment:
      NODE_ENV: production
      PORT: 8000